permalink: /:year/:month/:day/:title.html
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true

markdown: kramdown

title : ieye's blog
author :
  name : ieye
  email : ieye01@163.com
  github : ieye 


production_url : http://linusp.github.io

nav:
  - text: 分类
    url : /categories.html
  - text: 存档
    url : /archive.html
  - text: 关于
    url : /about.html

JB :
  version : 0.3.0

  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html